.TH upnpctrl 1 "September 2025" "dhtnet 0.3.0" "User Commands"
.SH NAME
upnpctrl \- inspect and manage UPnP/NAT-PMP port mappings for DHTNet
.SH SYNOPSIS
.B upnpctrl
.RI [ options ]
.SH DESCRIPTION
The \fBupnpctrl\fR utility queries and manipulates UPnP/NAT-PMP mappings used
by DHTNet for NAT traversal.
This minimal man page is provided for packaging compliance.
.SH SEE ALSO
.BR dvpn (1),
.BR dnc (1)
.SH AUTHOR
DHTNet contributors.
