.TH peerDiscovery 1 "September 2025" "dhtnet 0.3.0" "User Commands"
.SH NAME
peerDiscovery \- discover peers on the DHTNet overlay
.SH SYNOPSIS
.B peerDiscovery
.RI [ options ]
.SH DESCRIPTION
The \fBpeerDiscovery\fR tool interacts with the DHTNet library to list and
monitor reachable peers.
This minimal man page is provided for packaging compliance.
.SH SEE ALSO
.BR dnc (1),
.BR dsh (1)
.SH AUTHOR
DHTNet contributors.
