#!/bin/sh
set -e

umask 022

main() {
    mkdir -p /etc/dhtnet

    echo "===================="
    echo "dnc server installed."
    echo "To configure your dnc client and/or server, run:"
    echo "  dhtnet-crtmgr --interactive"
    echo "Server configuration is in /etc/dhtnet/dnc.yaml"
    echo "After configuration, enable and start server with:"
    echo "  systemctl enable dnc.service"
    echo "  systemctl start dnc.service"
    echo "===================="
}

main

#DEBHELPER#
