#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
	if systemctl list-unit-files | grep -q '^dnc.service'; then
		systemctl stop dnc.service >/dev/null 2>&1 || true
		systemctl disable dnc.service >/dev/null 2>&1 || true
	fi
fi

if [ -e /etc/systemd/system/dnc.service ]; then
	rm -f /etc/systemd/system/dnc.service
fi

#DEBHELPER#

exit 0
