FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential pkg-config cmake git wget meson \
    libtool \
    libncurses5-dev libreadline-dev nettle-dev \
    libgnutls28-dev libuv1-dev libjsoncpp-dev libargon2-dev \
    libssl-dev libfmt-dev libasio-dev libmsgpack-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN mkdir /usr/include/nonstd \
    && wget https://raw.githubusercontent.com/martinmoene/expected-lite/master/include/nonstd/expected.hpp \
    -O /usr/include/nonstd/expected.hpp

COPY dependencies/opendht /src/opendht

RUN cd /src/opendht && mkdir build && cd build \
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_TESTING=Off \
    -DOPENDHT_TOOLS=On \
    -DOPENDHT_PEER_DISCOVERY=Off \
    -DOPENDHT_PROXY_SERVER=Off \
    -DOPENDHT_PROXY_CLIENT=Off \
    && make -j$(nproc) && make install \
    && cd / && rm -rf /src

EXPOSE 4222/udp

ENTRYPOINT ["dhtnode"]
CMD ["-p", "4222", "--persist"]
