pipeline {
    agent any
    triggers {
        gerrit customUrl: '',
            gerritProjects: [
                [branches: [[compareType: 'PLAIN', pattern: 'master']],
                 compareType: 'PLAIN',
                 disableStrictForbiddenFileVerification: false,
                 pattern: 'dhtnet']],
            triggerOnEvents: [
                commentAddedContains('!build'),
                patchsetCreated(excludeDrafts: true, excludeNoCodeChange: true)]
    }
    options {
        ansiColor('xterm')
    }
    parameters {
            string(name: 'GERRIT_REFSPEC',
                   defaultValue: 'refs/heads/dhtnet',
                   description: 'The Gerrit refspec to fetch.')
    }
    stages {
        stage('SCM Checkout') {
            steps {
                checkout changelog: true, poll: false,
                    scm: [$class: 'GitSCM',
                        branches: [[name: 'FETCH_HEAD']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [$class: 'CloneOption', noTags: true, reference: '', shallow: true],
                            [$class: 'WipeWorkspace']],
                        submoduleCfg: [],
                        userRemoteConfigs: [[refspec: '${GERRIT_REFSPEC}', url: 'https://${JAMI_GERRIT_URL}/dhtnet']]]
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.build("dhtnet:${env.BUILD_ID}", "--target test .")
                }
            }
        }
        stage('Show result') {
            steps {
                script {
                    docker.run("dhtnet:${env.BUILD_ID}", "cat /result.summary")
                }
            }
        }
        stage('Show result') {
            steps {
                script {
                    shell """
                    id=$(docker create dhtnet:${env.BUILD_ID})
                    docker cp $id:/result result
                    docker rm -v $id
                    """
                    docker.run("dhtnet:${env.BUILD_ID}", "cat /result.summary")
                }
            }
        }
        stage('Upload') {
            def remoteHost = env.SSH_HOST_DL_RING_CX
            def remoteBaseDir = '/srv/repository/ring'
            sshagent(['5825b39b-dfc6-435f-918e-12acc1f56221']) {
                sh("rsync -a result ${remoteHost}:${remoteBaseDir}/docs/dhtnet/coverage/")
            }
        }
    }
}
